### PR TITLE
Block pressing the BetterDocs server in your list

### PR DESCRIPTION
**Pull request by FNCxPro**
Prevents you from clicking on the BetterDocs server in your list at all

### CODE REVIEW

**Comment by MasicoreLord** [comment]
That would prevent a user from right clicking to leave it.

**Comment by KyzaGitHub** [comment]
Why don't you just remove it from the list? The way you did it will drag the window if the user moves their mouse.

Just set the display to none imo.

**Comment by Zewia** [comment]
Setting the display to none would leave an empty space where the icon should be.

**Comment by MasicoreLord** [comment]
Has been up more than long enough, and not bothering w/ that.

**Pull request closed without merging**
